declare module '*.scss'
declare module '*.svg'
declare module '*.png'
declare module '*.jpeg'
declare module '*.gif'
declare module '*.bmp'
declare module '*.tiff'

declare module 'postcss-px2rem'
declare module 'postcss-autoreset'

declare module 'react-intl'
declare module 'react-transition-group'
declare module 'lodash'
declare module 'lodash/debounce'
declare module 'mobx'
declare module 'crypto-js'
declare module 'crypto-js/hmac-sha256'
declare module 'react-helmet'
declare module '@types/react-router-dom'
declare module '@api/api'
declare module 'antd'
declare module 'moment'
declare module 'antd/lib/locale-provider/zh_CN'
declare module 'classnames'
declare module 'mobx-react-lite'
declare module 'react-json-view'
